### ISSUE TITLE
Stream playback very slow

### ISSUE THREAD

**Issue by ferenczAndras** [iammert/RadioPlayerService#14]
Hello. I am using this library for a local radio, and i saw that few times when i start the radio, the playback is very very slow. If i stop the radio and restart it, than works ok. What can be the problem ?

**Comment by iammert** [comment]
I think It is aacdecoder library's problem. I could not provide any solution because I don't have knowledge about native development. I am sorry. @ferenczAndras

**Comment by FernandoCT** [comment]
I am having the same issue on an emulator (Genymotion) and on a Nexus 5 device :(
