### ISSUE TITLE
Service not registered

### ISSUE THREAD

**Issue by nestor-bonilla-s** [iammert/RadioPlayerService#17]
Hello,
thanks for this great library, but currently I'm having some issues with it.

When you are playing a x radio and you change the orientation you get an error: 
"Unable to destroy activity: java.lang.IllegalArgumentException: Service not registered:"
and of course the listener is lost and you cannot play or stop from the notification.

Would you help me please to solve this issue?

Best regards

**Comment by NeutronStein** [comment]
Did you declared your service in AndroidManifest.xml?

**Comment by nestor-bonilla-s** [comment]
Yes I did, what happens is that if you want to allow screen orientation change you need to overwrite the method onConfigurationChanged(), at leat this worked for me. Best regards

**Comment by colorgold** [comment]
How do you declare the service in AndroidManifest.xml? Is the service you're referring to the RadioPlayerService, or your own service?
