### ISSUE TITLE
How  to show  the songname ?

### ISSUE THREAD

**Issue by Ishu25** [iammert/RadioPlayerService#34]
I tried  but   unable to show  song title and artist name  in mainactivity using the code 
@Override
    public void onMetaDataReceived(String s, String s1) {
        //TODO Check metadata values. Singer name, song name or whatever you have.

```
}
```

Can  you tell  what  coding  should I do  in this part of code  for show  songname and also in the  notifications area. Thanks

**Comment by iammert** [comment]
Stream url should support metadata. I mean If you don't get notified with any metadata, then you stream url does not broadcast metadata.

**Comment by Ishu25** [comment]
But logcat  show  this   info which is right      
 IcyInputStream: Metadata string: StreamTitle='songname-artist';
but  I am  unable  to  display that  info  onto mainactivity. For that I have  to do  some  more  coding ?  or   what  else  I can  do to show songname ?

**Comment by Tyosensya** [comment]
please give O code in the curtain pls.

**Comment by hamdiwanis** [comment]
```
@Override
    public void onMetaDataReceived(String identifier, final String data) {
        if ("StreamTitle".equals(identifier)) {
            runOnUiThread(new Runnable() {
                @Override
                public void run() {
                    stateInfo.setText(data.toString());

                }
            });
        }
    }

```

hope it helps :)
