### ISSUE TITLE
how to open the app when click on notification ?

### ISSUE THREAD

**Issue by Ishu25** [iammert/RadioPlayerService#52]
I want that whenever I click on the notification then it will open the app directly . But as know I it would only open the the home screen of the mobile whenever I click on notification Rather then opening the app ?

**Comment by chehanr** [comment]
[Try this.](https://github.com/iammert/RadioPlayerService/wiki/Open-app-when-notification-is-clicked)

**Comment by Ishu25** [comment]
Thanku so much @chehanr , ur code works . But This  opens the  new activity and I want to resume the activity where I Leave or close the app . I mean If app is playing then there would be a stop button   but when I open that activity  from notification then it will open the new  activity where  play button is showed rather than resuming the activity . So plz provide the code so that main activity resumes when click on notification rather than open new activity. Thanks,

**Comment by chehanr** [comment]
You should try saving the play/ stop state of the button on Shared Preferences. so when you reopen the app the button remain on the play state rather than stop.

**Comment by Ishu25** [comment]
@chehanr  can u provide any code for this ?

**Comment by chehanr** [comment]
A better method is, 

```
     if (mRadioManager.isPlaying()) {
            mControlPlay_Pause.setImageResource(R.drawable.ic_pause);
        } else {
            mControlPlay_Pause.setImageResource(R.drawable.ic_play_arrow);
        }
```

**Comment by Ishu25** [comment]
hey @chehanr  where should I use this because in main activity it wil result in null pointer exception .

**Comment by Sarun1001** [comment]
@Ishu25 
add <android:launchMode="singleTop"> in your manifest under your launching activity after the above code implementation
eg : `   <activity android:name=".RadioMainActivity"
            android:theme="@style/AppThemeBar"
            android:launchMode="singleTop"
            android:configChanges="orientation|screenSize"/>`
