### ISSUE TITLE
Attempt to invoke virtual method 'void co.mobiwise.library.RadioPlayerService.play(java.lang.String)' on a null object reference

### ISSUE THREAD

**Issue by sbmvirdi** [iammert/RadioPlayerService#73]
i am trying to use this in fragment but this error is showing 
 mRadioManager = RadioManager.with(getActivity());
        mRadioManager.registerListener(this);
        mRadioManager.enableNotification(true);
        mRadioManager.connect();
            mRadioManager.startRadio(URL);

**Comment by Dr-Legend** [comment]
same for me to!

**Comment by sbmvirdi** [comment]
And he still has not replied

**Comment by HaiNH-wh** [comment]
i got same issue

**Comment by colorgold** [comment]
I remember getting this issue but forgot what I did. Here is the code I have in my fragment:
if (radioManager == null) 
{
    radioManager = RadioManager.with(getActivity().getApplicationContext());
    radioManager.registerListener(this);
    radioManager.setLogging(true); //this is optional 
 }

**Comment by sbmvirdi** [comment]
Well i thing using exo player is more better to stream audio from server! I hereby glose this issue
